import React from 'react'

const SellerOnboarding: React.FC = () => {
  return (
    <div className="min-h-screen bg-gray-50">
      <div className="container mx-auto px-6 py-8">
        {/* Progress Indicator */}
        <div className="mb-8">
          <div className="flex items-center justify-center space-x-8">
            {['Welcome', 'Document Upload', 'AI Processing', 'Form Review', 'Publish'].map((step, index) => (
              <div key={step} className="flex items-center">
                <div className={`w-8 h-8 rounded-full flex items-center justify-center text-sm font-medium ${
                  index === 0 ? 'bg-blue-600 text-white' : 'bg-gray-200 text-gray-600'
                }`}>
                  {index + 1}
                </div>
                <span className="ml-2 text-sm text-gray-600">{step}</span>
                {index < 4 && <div className="w-8 h-px bg-gray-300 ml-4"></div>}
              </div>
            ))}
          </div>
        </div>
        
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-8 h-[calc(100vh-250px)]">
          {/* Left Side - AI Guide */}
          <div className="bg-white rounded-lg shadow-lg flex flex-col">
            <div className="p-6 border-b border-gray-200">
              <div className="flex items-center gap-3">
                <div className="w-10 h-10 bg-blue-100 rounded-full flex items-center justify-center">
                  🤖
                </div>
                <div>
                  <h3 className="font-semibold text-gray-900">
                    AI Listing Assistant
                  </h3>
                  <p className="text-sm text-gray-600">
                    I'll help you create your property listing
                  </p>
                </div>
              </div>
            </div>
            
            <div className="flex-1 p-6 bg-gray-50 flex items-center justify-center">
              <p className="text-gray-500">AI Seller Chat Coming Soon...</p>
            </div>
            
            <div className="p-6 border-t border-gray-200">
              <div className="flex items-center gap-2">
                <input
                  type="text"
                  placeholder="Tell me about your property..."
                  className="flex-1 input"
                  disabled
                />
                <button className="btn-primary px-4" disabled>
                  Send
                </button>
              </div>
            </div>
          </div>
          
          {/* Right Side - Dynamic Form */}
          <div className="bg-white rounded-lg shadow-lg flex flex-col">
            <div className="p-6 border-b border-gray-200">
              <h3 className="text-xl font-bold text-gray-900">
                Property Listing Form
              </h3>
              <p className="text-gray-600 mt-1">
                AI-generated from your description
              </p>
            </div>
            
            <div className="flex-1 p-6 bg-gray-50 flex items-center justify-center">
              <div className="text-center">
                <p className="text-gray-500 mb-4">
                  Form will be generated as you chat with the AI assistant
                </p>
                <div className="grid grid-cols-2 gap-4">
                  <div className="skeleton h-10"></div>
                  <div className="skeleton h-10"></div>
                  <div className="skeleton h-10 col-span-2"></div>
                  <div className="skeleton h-20 col-span-2"></div>
                </div>
              </div>
            </div>
            
            <div className="p-6 border-t border-gray-200 bg-gray-50">
              <div className="flex justify-between items-center">
                <div className="text-sm text-gray-600">
                  ✨ 0 fields generated by AI
                </div>
                <div className="flex gap-3">
                  <button className="btn-outline" disabled>
                    Save Draft
                  </button>
                  <button className="btn-primary" disabled>
                    Publish Listing
                  </button>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}

export default SellerOnboarding 